---
# HelmRelease
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: express-app
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: express-app-prod
  chart:
    git: git@github.com:bambro/gitops-istio
    path: charts/webservice
    ref: master
  values:
    image: allclasspenguin/node-express-app:dev-00024
    replicaCount: 1
    service:
      port: 8080
    deployment:
      containerPort: 8080
    canary:
      enabled: true
      istioIngress:
        enabled: true
        gateway: public-gateway.istio-system.svc.cluster.local
        host: "*"
      loadtest:
        enabled: true
      helmtest:
        enabled: true
---
# Canary Analysis
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: express-app
  namespace: prod
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # service port number
    port: 8080
    # container port number or name (optional)
    targetPort: 8080
    # Istio gateways (optional)
    gateways:
    - public-gateway.istio-system.svc.cluster.local
    # Istio virtual service host names (optional)
    hosts:
    - "*"
    # Istio traffic policy (optional)
    trafficPolicy:
      tls:
        # use ISTIO_MUTUAL when mTLS is enabled
        mode: DISABLE
    # Istio retry policy (optional)
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  canaryAnalysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    # metrics
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      threshold: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      threshold: 500
      interval: 30s
    # testing (optional)
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.prod/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -sd 'test' http://express-app-canary:8080/"
      - name: load-test
        url: http://flagger-loadtester.prod/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://express-app-canary.prod:8080/status/200"