---
# HelmRelease
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: express-app
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: express-app-prod
  chart:
    git: git@github.com:bambro/gitops-istio
    path: charts/webservice
    ref: master
  values:
    image: allclasspenguin/node-express-app:dev-00029
    replicaCount: 1
    service:
      port: 8080
    deployment:
      containerPort: 8080
    canary:
      enabled: true
      istioIngress:
        enabled: false
      loadtest:
        enabled: true
        url: http://flagger-loadtester.prod/