{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: {{ template "webservice.fullname" . }}
  labels:
    app: {{ template "webservice.name" . }}
    chart: {{ template "webservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "webservice.fullname" . }}
  progressDeadlineSeconds: 30
  service:
    port: {{ .Values.service.port }}
    {{- if .Values.canary.istioIngress.enabled }}
    gateways:
    - {{ .Values.canary.istioIngress.gateway }}
    hosts:
    - {{ .Values.canary.istioIngress.host }}
    {{- end }}
    trafficPolicy:
      tls:
        mode: {{ .Values.canary.istioTLS }}
  canaryAnalysis:
{{ toYaml .Values.canary.config | indent 4 }}
{{- end }}