{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: {{ include "webservice.fullname" . }}
  labels:
    app: {{ include "webservice.name" . }}
    chart: {{ include "webservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "webservice.fullname" . }}
  progressDeadlineSeconds: 60
  service:
    port: {{ .Values.service.port }}
    {{- if .Values.canary.istioIngress.enabled }}
    gateways:
    - {{ .Values.canary.istioIngress.gateway }}
    hosts:
    - {{ .Values.canary.istioIngress.host }}
    {{- end }}
    trafficPolicy:
      tls:
        mode: {{ .Values.canary.istioTLS }}
  canaryAnalysis:
    interval: {{ .Values.canary.analysis.interval }}
    threshold: {{ .Values.canary.analysis.threshold }}
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    metrics:
    - name: request-success-rate
      threshold: {{ .Values.canary.thresholds.successRate }}
      interval: 1m
    - name: request-duration
      threshold: {{ .Values.canary.thresholds.latency }}
      interval: 30s
    webhooks:
      {{- if .Values.canary.loadtest.enabled }}
      - name: load-test
        url: {{ .Values.canary.loadtest.url }}
        timeout: 5s
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 5 -c 2 http://{{ include "webservice.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}"
          logCmdOutput: "true"
      {{- end }}
{{- end }}