apiVersion: v1
kind: Service
metadata:
  name: {{ template "webservice.fullname" . }}
  labels:
    app: {{ template "webservice.name" . }}
    chart: {{ template "webservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.service.annotations }}
  {{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}  
spec:
  type: {{ .Values.service.type }}
   {{ if eq .Values.service.type "LoadBalancer" }}
{{- if .Values.service.LoadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{toYaml  .Values.service.LoadBalancerSourceRanges | indent 4}}
{{- end }}
  {{if .Values.service.LoadBalancerIP }}
  loadBalancerIP: {{.Values.service.LoadBalancerIP}}
  {{end}}
  {{end}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
{{- if .Values.service.extraPorts }}
{{ toYaml .Values.service.extraPorts | indent 4 }}
{{- end }}
  selector:
    app: {{ template "webservice.fullname" . }}
    release: {{ .Release.Name }}
{{- if .Values.service.selectors }}
{{ toYaml .Values.service.selectors | indent 4 }}
{{- end }}