---
# HelmRelease
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: express-app
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: express-app-default
  chart:
    git: git@github.com:bambro/gitops-istio
    path: charts/webservice
    ref: master
  values:
    image: allclasspenguin/node-express-app:dev-00035
    replicaCount: 1
    service:
      port: 8080
    deployment:
      containerPort: 8080
    canary:
      enabled: true
      config:
        # interval: 1m
        threshold: 1
        # maxWeight: 50
        # stepWeight: 10
        # metrics:
        # - name: request-success-rate
        #   threshold: 99
        #   interval: 1m
        webhooks:
          - name: "integration tests"
            type: pre-rollout
            url: "http://jenkins-webhook-svc.default:8080/jenkins/webhook"
            timeout: 2m
            metadata:
              some: "message"