---
# HelmRelease
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: express-app
  namespace: flux
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: express-app-flux
  chart:
    git: git@github.com:bambro/gitops-istio
    path: charts/webservice
    ref: master
  values:
    image: allclasspenguin/node-express-app:dev-00036
    replicaCount: 1
    service:
      port: 8080
    deployment:
      containerPort: 8080
